package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import javafx.scene.input.MouseEvent;

public class RegisterController {
	@FXML
	private TextField regFirstNameTextField;
	@FXML
	private TextField regLastNameTextField;
	@FXML
	private TextField regPasswordTextField;
	@FXML
	private TextField regConfirmPasswordTextField;
	@FXML
	private TextField regEmailTextField;
	@FXML
	private Button registerUserBtn;
	@FXML
	private Label logInLink;

	// Event Listener on Button[#registerUserBtn].onAction
	@FXML
	public void registerBtnListener(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#logInLink].onMouseClicked
	@FXML
	public void logInLinkListener(MouseEvent event) throws IOException {
        Parent tableViewParent = FXMLLoader.load(getClass().getResource("Login.fxml"));
        Scene tableViewScene = new Scene(tableViewParent);
        
        Stage window = (Stage)((Node)event.getSource()).getScene().getWindow();
        
        window.setScene(tableViewScene);
        window.show();
	}
}
